### ISSUE TITLE
Alternative derivation of synths question

### ISSUE THREAD

**Issue by Orion-9R** [thorchain/docs#44]
Looking at the alternative derivation of synths doc: https://docs.thorchain.org/thorchain-finance/synthetic-asset-model

We see the following: 
![image](https://user-images.githubusercontent.com/89870314/160457676-fa054e9a-abc0-4db0-8f01-6905e4f55f72.png)

Based on these definitions $$U = S$$, Dynamically calculated synth units = Total Supply of Synth Asset.

However that doesn't seem correct.

**Comment by Multipartite** [comment]
For
S = Synth Supply
A = Asset Depth
L = Liquidity Units
U = Synth Units

I agree that it looks as though S has been accidentally used instead of U in the last step (and that S should not equal U):
'the ratio of synth units to LP units' should be U/L, not S/L.

The right side of the equation looks correct as described, also equal to the below:

Ratio of {synth Asset-backing} to {pool Asset depth without synth Asset-backing} (given that synth is always half backed by Asset and half backed by RUNE):
(0.5*S) / (A - 0.5*S)
= S / (2A - S)

**Comment by Orion-9R** [comment]
This was fixed
